### ISSUE TITLE
위치 설정 요청 RuntimeException 오류

### ISSUE THREAD

**Issue by hummingengineer** [gasbank/rolling_geofence#1]
<운영체제>
- 안드로이드

<문제>
- 안드로이드 위치 설정이 OFF 되어 있는 상태에서 위치 기능을 사용하면, 위치 설정 ON을 요청하는 알림창이 생성된다.
- 생성된 알림창에서 확인 버튼이나 거절 버튼을 누를 때, 대부분의 경우 정상작동 했으나, 한 번씩 아래와 같은 오류가 뜨며 앱이 강제 종료되는 문제가 발생한다.

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=Intent { dat= }} to activity {}: java.lang.NullPointerException
```

**Comment by hummingengineer** [comment]
<분석>
- 해당 오류 문구에 Failure delivering result ResultInfo가 있는 것을 보아 onActivityResult와 관련있다고 추측
- 또한 java.lang.NullPointerException이라는 문구가 있는 것을 보아 data 전송될 때, null 처리가 되지 않고 있다고 추측

<해결>
- 01db16daa23065f537d4cd2f31cc8bcb7f9a3ebb
- rolling_geofence에서 응답을 담당하는 부분인 onActivityResult에 data가 null일 경우 조건문을 추가해서 해결함
- 해당 코드 추가 이후 문제가 해결됨

**Comment by gasbank** [comment]
(https://github.com/lovealarm/joalarm_flutter/issues/229#issuecomment-1962221983 본문에서 복사한 내용)

수정해 주신 커밋을 곰곰이 살펴보니, 해결된 방식이 좀 의아해서 자세히 봤습니다.

null 체크하신 data 변수는 실제로 코드 내에서 쓰지도 않는 변수인데, 쓰지 않는 변수의 null 체크를 추가해서 문제가 해결됐다는 게 이상했습니다.

즉, 비정상 종료 문제가 해결되었지만 것은 맞지만, 수정 방식은 틀린 것으로 보입니다.

알려주신 스택트레이스 상으로 오류가 일어난 지점이 top.plusalpha.rolling_geofence.RollingGeofencePlugin.onActivityResult(RollingGeofencePlugin.kt:698) 부분이므로, 이 부분에 입각해서 올바르게 다시 한번 살펴보시고 제대로 수정해주시죠!

**Comment by hummingengineer** [comment]
<분석>
- resultCallbackMap[START_SINGLE_LOCATION_REQUEST_CODE]이 null 값일 때, 처리가 되어 있지 않음

<해결>
- 902930f9b45a7a657e2f7c5474003858bb1af6f1
- resultCallbackMap[START_SINGLE_LOCATION_REQUEST_CODE]이 null 값일 때, 처리하는 로직을 추가함

**Comment by gasbank** [comment]
좋습니다!! #2 이슈에서 제가 이어서 좀 더 살펴보겠습니다. :)
