### ISSUE TITLE
startSingleLocationRequest 처리 중 예외 올바르게 처리하기

### ISSUE THREAD

**Issue by gasbank** [gasbank/rolling_geofence#2]
위치 기능 자체를 꺼 둔 상태 등 유저가 부여하는 권한 밖의 이슈로 인해 현재 위치 조회에 실패하는 경우 `startSingleLocationRequest` 요청을 제대로 처리하지 못하게 된다. 이 때 처리 결과의 반환값이 정상 케이스와 다르게 오는 것으로 보이는데, 이에 대해 우아하게 처리하면 좋겠다.

```
E/flutter (24874): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Iterable<dynamic>'
E/flutter (24874): #0      MethodChannelRollingGeofence.startSingleLocationRequest (package:rolling_geofence/rolling_geofence_method_channel.dart:87:34)
E/flutter (24874): <asynchronous suspension>
E/flutter (24874): #1      _CrossingHomeInnerPageState.fetchCurrentPosition (package:joalarm_flutter/crossing_home.dart:515:22)
E/flutter (24874): <asynchronous suspension>
E/flutter (24874): #2      _CrossingHomeInnerPageState._postCurrentPositionSegment.<anonymous closure> (package:joalarm_flutter/crossing_home.dart:462:40)
E/flutter (24874): <asynchronous suspension>
E/flutter (24874): 
```

**Comment by gasbank** [comment]
어쩌면 https://github.com/lovealarm/joalarm_flutter/issues/216 연관 있을 수도?

**Comment by gasbank** [comment]
참고로 이 문제는 01db16daa23065f537d4cd2f31cc8bcb7f9a3ebb 커밋에 의해 문제가 가려지게 되었다.
문제점을 확인하기 위해서는 다음 절차를 따른다.

1. 01db16daa23065f537d4cd2f31cc8bcb7f9a3ebb 커밋을 리버트한다.
2. 기기 설정에서 위치 기능 자체를 끈다.
3. Android 테스트 앱을 실행해서 '현재 위치 조회'를 누른다.
4. Android OS 레벨에서 위치 기능이 켜져야 한다는 안내 메시지 팝업이 뜨면, 거절한다.
5. 예외 발생을 확인한다.

**Comment by gasbank** [comment]
https://github.com/lovealarm/joalarm_flutter/issues/229 이슈가 해결된 다음에 이어서 본다.

**Comment by gasbank** [comment]
후후 잘 부탁드립니다.

**Comment by hummingengineer** [comment]
<분석>
- (1) flutter plugin의 startSingleLocationRequest() 메소드의 반환타입은 `Future<List<double>>`이다.
- (2) 안드로이드 네이티브 코드의 onActivityResult() 함수에서 '위치 기능 켜기'를 거절했을 때 반환하는 값의 타입은 `String`이다.
- (1), (2)의 반환값이 일치하지 않아 문제가 발생하는 오류

<해결>
- c57a90833ee5baba8c71882c23a9645f4639c7bd
- 안드로이드 네이티브 코드 쪽에서 String으로 값을 반환했을 때를 체크한 다음 if 구문을 통해 분기 처리를 하여 문제 해결
- 발생한 오류를 콘솔에 출력해주고, 거절했을 때는 현재 위치가 존재하지 않으므로 빈 배열로 반환하여 반환 타입을 일치 시켜 문제 해결

**Comment by gasbank** [comment]
반환값이 `double 배열`이나 `String` 두 가지 뿐이므로 지금 코드도 유효한 수정이긴 하지만, 더 확실히 안전하게 처리하려면 `double 배열`인 걸 체크해서 했으면 어떨까 합니다. 가능성은 낮지만 반환값에 이상한 타입이 또 추가된다든지 하면 이런 문제가 반복될 수 있으니까요
