### ISSUE TITLE
onActivityResult resultCode가 0일 때, 코드 재검토 요청

### ISSUE THREAD

**Issue by hummingengineer** [gasbank/rolling_geofence#3]
- Denied 메시지를 전송하는데, .error가 아니라 .success로 되어 있습니다. 해당 코드가 맞는지 검토 부탁드립니다.

https://github.com/gasbank/rolling_geofence/blob/902930f9b45a7a657e2f7c5474003858bb1af6f1/android/src/main/kotlin/top/plusalpha/rolling_geofence/RollingGeofencePlugin.kt#L694

**Comment by gasbank** [comment]
권한 허용이나 거부가 확인되는 경우에는 success로 처리했고, 그 밖의 애매한 상황만 error로 처리했습니다. 다른 success 호출도 참고하시죠!

**Comment by gasbank** [comment]
노파심에 드리는 말씀이지만, 제 의도가 이해가 되셨다면 그걸로 된 겁니다. ㅎㅎ

더 좋은 코드나 구조가 있다면, 또는 제 의도엔 동의하시지만 그 의도와는 맞지 않는 이상한 코드가 있다면 적극적으로 고쳐주시면 되겠습니다.
